name: Main
on: [push]
jobs:
    ci:
        runs-on: ubuntu-latest
        env:
            VITE_BASE_URL: https://api.voicefu.com
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.14'
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm i
            - run: npm run lint
            - run: npm run pretty
            - run: npm run tsc
            - run: npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOICEFU_2ED11 }}'
                  channelId: live
                  projectId: voicefu-2ed11
